clone_depth: 50

branches:
  only:
    - master

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      CONFIGURATION: Release
      XCODE_VERSION: 9.4.1
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
      CONFIGURATION: Debug
      XCODE_VERSION: 10.3
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
      CONFIGURATION: Release
      XCODE_VERSION: 11.7
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
      CONFIGURATION: Debug
      XCODE_VERSION: 12.3
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-bigsur
      CONFIGURATION: Release
      XCODE_VERSION: 12.5.1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 12 2013
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 12 2013 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      AUDIO_DRIVER: Wasapi
      CONFIGURATION: Debug
      GENERATOR: Visual Studio 12 2013 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 14 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      AUDIO_DRIVER: Asio
      CONFIGURATION: Debug
      GENERATOR: Visual Studio 14 2015 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 14 2015 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      AUDIO_DRIVER: Wasapi
      CONFIGURATION: Release
      GENERATOR: Visual Studio 14 2015 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 15 2017 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 16 2019

install:
  - git submodule update --init --recursive

for:
  - matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
        - APPVEYOR_BUILD_WORKER_IMAGE: macos
        - APPVEYOR_BUILD_WORKER_IMAGE: macos-bigsur
    build_script:
      - sudo xcode-select -s /Applications/Xcode-$XCODE_VERSION.app
      - python ci/configure.py --generator Xcode
      - python ci/build.py --configuration $CONFIGURATION
  - matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    build_script:
      - python ci/configure.py --audio-driver %AUDIO_DRIVER% --generator "%GENERATOR%"
      - python ci/build.py --configuration %CONFIGURATION%

test_script:
  - python ci/run-tests.py --target LinkCoreTest
  - python ci/run-tests.py --target LinkDiscoveryTest
