clone_depth: 50

branches:
  only:
    - master

# Also includes VS2013 pre-installed
image: Visual Studio 2015

environment:
  matrix:
    # Visual Studio 2013, 32-bit Release, Asio driver
    - AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 12 2013
      QT: msvc2013
    # Visual Studio 2013, 64-bit Release, Asio driver
    - AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 12 2013 Win64
      QT: msvc2013_64
    # Visual Studio 2015, 32-bit Release, Asio driver
    - AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 14 2015
      QT: msvc2013
    # Visual Studio 2015, 64-bit Debug, Asio driver
    - AUDIO_DRIVER: Asio
      CONFIGURATION: Debug
      GENERATOR: Visual Studio 14 2015 Win64
      QT: msvc2013_64
    # Visual Studio 2015, 64-bit Release, Asio driver
    - AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 14 2015 Win64
      QT: msvc2013_64
    # Visual Studio 2015, 64-bit Release, Wasapi driver
    - AUDIO_DRIVER: Wasapi
      CONFIGURATION: Release
      GENERATOR: Visual Studio 14 2015 Win64
      QT: msvc2013_64

install:
  - git submodule update --init --recursive
  - set PATH=%PATH%;C:\Qt\5.5\%QT%\bin

build_script:
  - python ci/configure.py -q -a %AUDIO_DRIVER% -g "%GENERATOR%"
  - python ci/build.py --configuration %CONFIGURATION%

test_script:
  - python ci/run-tests.py --target LinkCoreTest
  - python ci/run-tests.py --target LinkDiscoveryTest
