clone_depth: 50

branches:
  only:
    - master

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 12 2013
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 12 2013 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      AUDIO_DRIVER: Wasapi
      CONFIGURATION: Debug
      GENERATOR: Visual Studio 12 2013 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 14 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      AUDIO_DRIVER: Asio
      CONFIGURATION: Debug
      GENERATOR: Visual Studio 14 2015 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 14 2015 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      AUDIO_DRIVER: Wasapi
      CONFIGURATION: Release
      GENERATOR: Visual Studio 14 2015 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 15 2017 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      AUDIO_DRIVER: Asio
      CONFIGURATION: Release
      GENERATOR: Visual Studio 16 2019

install:
  - git submodule update --init --recursive

build_script:
  - python ci/configure.py --audio-driver %AUDIO_DRIVER% --generator "%GENERATOR%"
  - python ci/build.py --configuration %CONFIGURATION%

test_script:
  - python ci/run-tests.py --target LinkCoreTest
  - python ci/run-tests.py --target LinkDiscoveryTest
